// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: Datamesh/proto/datamesh.proto

package datameshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block message
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Height        int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Transaction message
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Blob message (for DA)
type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Commitment    string                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{2}
}

func (x *Blob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Blob) GetCommitment() string {
	if x != nil {
		return x.Commitment
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PostBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBlobRequest) Reset() {
	*x = PostBlobRequest{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBlobRequest) ProtoMessage() {}

func (x *PostBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBlobRequest.ProtoReflect.Descriptor instead.
func (*PostBlobRequest) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{5}
}

func (x *PostBlobRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBlobResponse) Reset() {
	*x = PostBlobResponse{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBlobResponse) ProtoMessage() {}

func (x *PostBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBlobResponse.ProtoReflect.Descriptor instead.
func (*PostBlobResponse) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{6}
}

func (x *PostBlobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SampleBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleBlobRequest) Reset() {
	*x = SampleBlobRequest{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleBlobRequest) ProtoMessage() {}

func (x *SampleBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleBlobRequest.ProtoReflect.Descriptor instead.
func (*SampleBlobRequest) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{7}
}

func (x *SampleBlobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SampleBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleBlobResponse) Reset() {
	*x = SampleBlobResponse{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleBlobResponse) ProtoMessage() {}

func (x *SampleBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleBlobResponse.ProtoReflect.Descriptor instead.
func (*SampleBlobResponse) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{8}
}

func (x *SampleBlobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxRequest) Reset() {
	*x = ExecuteTxRequest{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxRequest) ProtoMessage() {}

func (x *ExecuteTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTxRequest) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteTxRequest) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

type ExecuteTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxResponse) Reset() {
	*x = ExecuteTxResponse{}
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxResponse) ProtoMessage() {}

func (x *ExecuteTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Datamesh_proto_datamesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTxResponse) Descriptor() ([]byte, []int) {
	return file_Datamesh_proto_datamesh_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteTxResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_Datamesh_proto_datamesh_proto protoreflect.FileDescriptor

const file_Datamesh_proto_datamesh_proto_rawDesc = "" +
	"\n" +
	"\x1dDatamesh/proto/datamesh.proto\x12\bdatamesh\"\x88\x01\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\ftransactions\x18\x02 \x03(\v2\x15.datamesh.TransactionR\ftransactions\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x03R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"1\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"J\n" +
	"\x04Blob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\tR\n" +
	"commitment\"\x0f\n" +
	"\rStatusRequest\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"%\n" +
	"\x0fPostBlobRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\x10PostBlobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11SampleBlobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x12SampleBlobResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\x10ExecuteTxRequest\x12\x0e\n" +
	"\x02tx\x18\x01 \x01(\fR\x02tx\"+\n" +
	"\x11ExecuteTxResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2R\n" +
	"\x10ConsensusService\x12>\n" +
	"\tGetStatus\x12\x17.datamesh.StatusRequest\x1a\x18.datamesh.StatusResponse2\x97\x01\n" +
	"\tDAService\x12A\n" +
	"\bPostBlob\x12\x19.datamesh.PostBlobRequest\x1a\x1a.datamesh.PostBlobResponse\x12G\n" +
	"\n" +
	"SampleBlob\x12\x1b.datamesh.SampleBlobRequest\x1a\x1c.datamesh.SampleBlobResponse2X\n" +
	"\x10ExecutionService\x12D\n" +
	"\tExecuteTx\x12\x1a.datamesh.ExecuteTxRequest\x1a\x1b.datamesh.ExecuteTxResponseB4Z2github.com/datamesh-labs/datamesh/proto;datameshpbb\x06proto3"

var (
	file_Datamesh_proto_datamesh_proto_rawDescOnce sync.Once
	file_Datamesh_proto_datamesh_proto_rawDescData []byte
)

func file_Datamesh_proto_datamesh_proto_rawDescGZIP() []byte {
	file_Datamesh_proto_datamesh_proto_rawDescOnce.Do(func() {
		file_Datamesh_proto_datamesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Datamesh_proto_datamesh_proto_rawDesc), len(file_Datamesh_proto_datamesh_proto_rawDesc)))
	})
	return file_Datamesh_proto_datamesh_proto_rawDescData
}

var file_Datamesh_proto_datamesh_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Datamesh_proto_datamesh_proto_goTypes = []any{
	(*Block)(nil),              // 0: datamesh.Block
	(*Transaction)(nil),        // 1: datamesh.Transaction
	(*Blob)(nil),               // 2: datamesh.Blob
	(*StatusRequest)(nil),      // 3: datamesh.StatusRequest
	(*StatusResponse)(nil),     // 4: datamesh.StatusResponse
	(*PostBlobRequest)(nil),    // 5: datamesh.PostBlobRequest
	(*PostBlobResponse)(nil),   // 6: datamesh.PostBlobResponse
	(*SampleBlobRequest)(nil),  // 7: datamesh.SampleBlobRequest
	(*SampleBlobResponse)(nil), // 8: datamesh.SampleBlobResponse
	(*ExecuteTxRequest)(nil),   // 9: datamesh.ExecuteTxRequest
	(*ExecuteTxResponse)(nil),  // 10: datamesh.ExecuteTxResponse
}
var file_Datamesh_proto_datamesh_proto_depIdxs = []int32{
	1,  // 0: datamesh.Block.transactions:type_name -> datamesh.Transaction
	3,  // 1: datamesh.ConsensusService.GetStatus:input_type -> datamesh.StatusRequest
	5,  // 2: datamesh.DAService.PostBlob:input_type -> datamesh.PostBlobRequest
	7,  // 3: datamesh.DAService.SampleBlob:input_type -> datamesh.SampleBlobRequest
	9,  // 4: datamesh.ExecutionService.ExecuteTx:input_type -> datamesh.ExecuteTxRequest
	4,  // 5: datamesh.ConsensusService.GetStatus:output_type -> datamesh.StatusResponse
	6,  // 6: datamesh.DAService.PostBlob:output_type -> datamesh.PostBlobResponse
	8,  // 7: datamesh.DAService.SampleBlob:output_type -> datamesh.SampleBlobResponse
	10, // 8: datamesh.ExecutionService.ExecuteTx:output_type -> datamesh.ExecuteTxResponse
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_Datamesh_proto_datamesh_proto_init() }
func file_Datamesh_proto_datamesh_proto_init() {
	if File_Datamesh_proto_datamesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Datamesh_proto_datamesh_proto_rawDesc), len(file_Datamesh_proto_datamesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_Datamesh_proto_datamesh_proto_goTypes,
		DependencyIndexes: file_Datamesh_proto_datamesh_proto_depIdxs,
		MessageInfos:      file_Datamesh_proto_datamesh_proto_msgTypes,
	}.Build()
	File_Datamesh_proto_datamesh_proto = out.File
	file_Datamesh_proto_datamesh_proto_goTypes = nil
	file_Datamesh_proto_datamesh_proto_depIdxs = nil
}
